
seed: 907

Physics: 
  pde: 'Navier-Stokes'
  source: 'Spectral' 
  field: 'u, v, p'
  variables: 3
  Nx: 128
  Ny: 128
  Nt: 100
  rollout: 'RK4'
  physics normalisation: False

Model:
  arch: 'FNO'
  modes: 8
  width: 16
  act: 'gelu'
  physical operators: False
  operator splitting: False

Data: 
  name: 'NS_Spectral_combined.npz'
  loc: '/home/ir-gopa2/rds/rds-ukaea-ap001/ir-gopa2/Code/Neural_PDE/Data'
  ntrain: 100
  batch size: 1
  t_in: 1
  t_out: 50
  step: 1
  normalisation: 'Min-Max'

Opt:
  optimizer: 'adam'
  epochs: 500
  learning rate: 0.005
  beta1: 0.9
  beta2: 0.9
  weight decay: 1e-4
  scheduler: 'step'  # Or 'CosineAnnealingLR' OR 'ReduceLROnPlateau'
  scheduler step : 100
  scheduler gamma: 0.5
  grad_clip: 2.0

Train: 
  loss: 'LP'
  rollout: True
  checkpoint:
    epochs: 50
  restart: False
  restart run name: 

Simvue:
  mode: 'online'
  name: None # If None, config will be used but you can override it here
  folder: '/Neural_PDE/tests' 
