seed: 'random'

Physics: 
  pde: 'Euler-Fluid'
  source: 'Finite Volume' 
  field: 'rho, u, v, p'
  variables: 4
  Nx: 128
  Ny: 128
  Nt: 101
  dx: 0.0078125
  dy: 0.0078125
  dt: 0.02
  x_slice: 1
  y_slice: 1
  t_slice: 1
  physics_normalisation: False
  conservative: False

Model:
  arch: 'ViT'
  patch_size: 4
  embed_dim: 512
  in_vars: 4
  out_vars: 4
  time_channels: 1
  depth: 12
  num_heads: 10
  operator_splitting: False
  ops_split_normalise: False


Data: 
  name: 'NS_FV_combined_pitagora.npz'
  loc: '/pitagora_work/FUPB1_UKAEA_ML/vgopakum/Data/PMocz_Euler'
  ntrain: 100
  test_train_split: 0.2
  batch_size: 10
  t_in: 1
  t_out: 50
  step: 1
  normalisation: 'Min-Max_variable'

Opt:
  optimizer: 'adam'
  epochs: 250
  learning_rate: 0.005
  beta1: 0.9
  beta2: 0.9
  weight_decay: 1e-4
  scheduler: 'step'  
  scheduler_step : 100
  scheduler_gamma: 0.5
  grad_clip: 2.0

Train: 
  loss: 'LP'
  input_length: 1
  rollout_length: 5
  input_noise: 0.0
  odesolve: 
    source: 'custom' #'torchdiffeq', 'custom'
    method: 'AR' # 'AR', 'euler', 'midpoint', rk4'
    adjoint: False #Only for torchdiffeq
  batch_norm: False
  checkpoint:
    epochs: 300
  restart: False
  restart_run_name: '' #simvue run name 
  finetune: False
  finetune_run_name: 'happy-ray' 

Simvue:
  mode: 'offline'
  name: None 
  folder: '/Neural_PDE/Euler' 
  tags: 'ErrorBars'
