seed: 907

Physics: 
  pde: 'Euler-Fluid'
  source: 'Finite Volume' 
  field: 'rho, u, v, p'
  variables: 4
  Nx: 128
  Ny: 128
  Nt: 101
  dx: 0.0078125
  dy: 0.0078125
  dt: 0.02
  x_slice: 1
  y_slice: 1
  t_slice: 1
  physics_normalisation: False
  conservative: True

Model:
  arch: 'FNO'
  in_vars: 4
  out_vars: 4
  modes: 12
  width: 24
  n_layers: 4
  act: 'gelu'
  operator_splitting: False
  ops_split_normalise: False

Data: 
  name: 'NS_FV_combined_pitagora.npz'
  loc: '/pitagora_work/FUPB1_UKAEA_ML/vgopakum/Data/PMocz_Euler'
  ntrain: 500
  test_train_split: 0.2
  batch_size: 40
  t_in: 1
  t_out: 50
  step: 1
  normalisation: 'Min-Max'

Opt:
  optimizer: 'adam'
  epochs: 500
  learning_rate: 0.005
  beta1: 0.9
  beta2: 0.9
  weight_decay: 1e-4
  scheduler: 'step'  
  scheduler_step : 100
  scheduler_gamma: 0.5
  grad_clip: 2.0

Train: 
  loss: 'LP'
  input_length: 1
  rollout_length: 20
  input_noise: 0.0
  odesolve: 
    source: 'custom' #'torchdiffeq', 'custom'
    method: 'AR' # 'AR', 'euler', 'midpoint', rk4'
    adjoint: False #Only for torchdiffeq
  batch_norm: False
  checkpoint:
    epochs: 100
  restart: False
  restart_run_name: '' #simvue run name 

Simvue:
  mode: 'offline'
  name: None 
  folder: '/Neural_PDE/Euler' 
