
seed: 907

Physics: 
  pde: 'Comp. Navier-Stokes'
  source: 'PDEBench' 
  coeff: 'M0.1_Eta0.1_Zeta0.1'
  field: 'u, v, p, rho'
  variables: 4
  Nx: 128
  Ny: 128
  Nt: 21
  dx: 0.0078
  dy: 0.0078
  dt: 0.05
  x_slice: 1
  y_slice: 1
  t_slice: 1 
  physics normalisation: False

Model:
  arch: 'FNO'
  in_vars: 4
  out_vars: 4
  modes: 8
  width: 16
  n_layers: 4
  act: 'gelu'
  operator splitting: False
  ops_split normalise: False
  
Data: 
  name: '2D_CFD_Rand_M0.1_Eta0.01_Zeta0.01_periodic_128_Train.hdf5' #and others
  loc: '/home/ir-gopa2/rds/rds-ukaea-ap001/ir-gopa2/Data/PDEBench/pdebench/2D/CFD/2D_Train_Rand/'
  ntrain: 100
  test-train-split: 0.2
  batch size: 10
  t_in: 1
  t_out: 20
  step: 1
  normalisation: 'Min-Max_variable'

Opt:
  optimizer: 'adam'
  epochs: 500
  learning rate: 0.005
  beta1: 0.9
  beta2: 0.9
  weight_decay: 1e-4
  scheduler: 'step'  
  scheduler step : 100
  scheduler gamma: 0.5
  grad_clip: 2.0

Train: 
  loss: 'LP'
  input_length: 1
  input_noise: 0.0
  rollout_length: 10
  odesolve: 
    source: 'custom' #'torchdiffeq', 'custom'
    method: 'euler' # 'AR', 'euler', 'midpoint', rk4'
    adjoint: False #Only for torchdiffeq
  batch_norm: False
  checkpoint:
    epochs: 100
  restart: False
  restart run name: '' #simvue run name 

Simvue:
  mode: 'online'
  name: None 
  folder: '/Neural_PDE/Compressible_NS' 
