
seed: 907

Physics: 
  pde: 'Navier-Stokes'
  source: 'Spectral' 
  field: 'u, v, p'
  variables: 3
  Nx: 100
  Ny: 100
  Nt: 100
  dt: 0.01
  rollout: 'AR'
  physics_normalisation: False

Model:
  arch: 'CNO'
  Nx: 100
  N_layers: 3
  N_res: 2
  N_res_neck: 2
  in_channels: 3
  out_channels: 3
  channel_multiplier: 16
  operator_splitting: False


Data: 
  name: 'NS_Spectral_combined.npz'
  loc: '/home/ir-gopa2/rds/rds-ukaea-ap001/ir-gopa2/Code/Neural_PDE/Data'
  ntrain: 100
  test_train_split: 0.2
  batch_size: 1
  t_in: 1
  t_out: 50
  step: 1
  normalisation: 'Min-Max'

Opt:
  optimizer: 'adam'
  epochs: 500
  learning_rate: 0.005
  beta1: 0.9
  beta2: 0.9
  weight_decay: 1e-4
  scheduler: 'step'  
  scheduler_step: 100
  scheduler_gamma: 0.5
  grad_clip: 2.0

Train: 
  loss: 'LP'
  rollout: True
  checkpoint:
    epochs: 100
  restart: False
  restart_run_name: '' #simvue run name to restart from. 

Simvue:
  mode: 'online'
  name: None 
  folder: '/Neural_PDE/tests' 
