seed: 907

Physics: 
  pde: 'Wave'
  source: 'Spectral' 
  field: 'u'
  variables: 1
  Nx: 64
  Ny: 64
  Nt: 120
  dx: 0.0317
  dy: 0.0317
  dt: 0.0076 #1.5e-6 real time
  x_slice: 1
  y_slice: 1
  t_slice: 1
  physics_normalisation: False

Model:
  arch: 'CNO'
  Nx: 64
  N_layers: 2
  N_res: 2
  N_res_neck: 2
  in_channels: 1
  out_channels: 1
  channel_multiplier: 16
  operator_splitting: False
  ops_split_normalise: False

Data: 
  name: 'Wave_spectral_LHS.npz'
  loc: '/home/ir-gopa2/rds/rds-ukaea-ap001/ir-gopa2/Code/NOs_for_POs/Data'
  ntrain: 1000
  test_train_split: 0.2
  batch_size: 50
  t_in: 1
  t_out: 50
  step: 1
  normalisation: 'Min-Max'

Opt:
  optimizer: 'adam'
  epochs: 500
  learning_rate: 0.005
  beta1: 0.9
  beta2: 0.9
  weight_decay: 1e-4
  scheduler: 'step'  
  scheduler_step: 100
  scheduler_gamma: 0.5
  grad_clip: 2.0

Train: 
  loss: 'LP'
  input_length: 1
  rollout_length: 50
  input_noise: 0.0
  odesolve: 
    source: 'custom' #'torchdiffeq', 'custom'
    method: 'AR' # 'AR', 'euler', 'midpoint', rk4'
    adjoint: False #Only for torchdiffeq
  batch_norm: False
  checkpoint:
    epochs: 100
  restart: False
  restart_run_name: '' #simvue run name

Simvue:
  mode: 'online'
  name: None 
  folder: '/Neural_PDE/Wave' 