seed: 907

Physics: 
  pde: 'FDS'
  source: 'Finite Volume' 
  # variable: 'Temperature'
  # field: 'T1, T2, T3, T4, T5'
  variable: 'Smoke'
  field: 'V1, V2, V3, V4, V5'
  variables: 5 #Floors
  Nx: 101
  Ny: 31
  Nt: 120
  dx: 1.0
  dy: 1.0
  dt: 15
  x_slice: 1
  y_slice: 1
  t_slice: 4
  physics normalisation: False

Model:
  arch: 'UNet'
  in_vars: 5
  out_vars: 5
  act: 'gelu'
  operator splitting: False
  ops_split norm: False


Data: 
  name: 'TEMPS_COMBINED.npz'
  loc: '/home/ir-gopa2/rds/rds-ukaea-ap001/ir-gopa2/Code/NOs_for_POs/FDS/Data'
  ntrain: 245
  test-train-split: 0.2
  batch size: 20
  t_in: 1
  t_out: 10
  step: 1
  normalisation: 'Min-Max'

Opt:
  optimizer: 'adam'
  epochs: 500
  learning rate: 0.005
  beta1: 0.9
  beta2: 0.9
  weight_decay: 1e-4
  scheduler: 'step'  
  scheduler step : 100
  scheduler gamma: 0.5
  grad_clip: 2.0

Train: 
  loss: 'LP'
  input_length: 1
  rollout_length: 10
  input_noise: 0.0
  odesolve: 
    source: 'custom' #'torchdiffeq', 'custom'
    method: 'AR' # 'AR', 'euler', 'midpoint', rk4'
    adjoint: False #Only for torchdiffeq
  batch_norm: False
  checkpoint:
    epochs: 100
  restart: False
  restart run name: '' #simvue run name 

Simvue:
  mode: 'online'
  name: None 
  folder: '/FDS' 
