
seed: 907

Physics: 
  pde: 'Euler-Fluid'
  source: 'Finite Volume' 
  field: 'u, v, p, rho'
  variables: 4
  Nx: 128
  Ny: 128
  Nt: 101
  dt: 0.01
  x_slice: 2
  y_slice: 2
  t_slice: 2 
  physics normalisation: False

Model:
  arch: 'FNO'
  in_vars: 4
  out_vars: 4
  modes: 16
  width: 32
  n_layers: 3
  act: 'gelu'
  operator splitting: True

Data: 
  name: 'NS_FV_combined.npz'
  loc: '/home/ir-gopa2/rds/rds-ukaea-ap001/ir-gopa2/Code/Neural_PDE/Data'
  ntrain: 100
  test-train-split: 0.2
  batch size: 20
  t_in: 1
  t_out: 50
  step: 1
  normalisation: 'Min-Max_variable'

Opt:
  optimizer: 'adam'
  epochs: 500
  learning rate: 0.005
  beta1: 0.9
  beta2: 0.9
  weight_decay: 1e-4
  scheduler: 'step'  
  scheduler step : 100
  scheduler gamma: 0.5
  grad_clip: 2.0

Train: 
  loss: 'LP'
  input_length: 1
  rollout_length: 10
  input_noise: 0.0
  odesolve: 
    source: 'custom' #'torchdiffeq', 'custom'
    method: 'euler' # 'AR', 'euler', 'midpoint', rk4'
    adjoint: False #Only for torchdiffeq
  checkpoint:
    epochs: 100
  restart: False
  restart run name: '' #simvue run name 

Simvue:
  mode: 'online'
  name: None 
  folder: '/Neural_PDE/Euler' 
