
seed: 907

Physics: 
  pde: 'MHD'
  source: 'JOREK'
  field: 'rho, phi, T'
  variables: 3
  Nx: 100
  Ny: 100
  Nt: 200
  rollout: 'AR'
  physics normalisation: False

Nodel:
  arch: 'FNO'
  modes: 8
  width: 16
  variables: 3
  act: 'gelu'
  physical operators: False
  operator splitting: False

Data: 
  name: 'JOREK_filtered.npz'
  loc: '/home/ir-gopa2/rds/rds-ukaea-ap001/ir-gopa2/Code/NOs_for_POs/Data'
  ntrain: 100
  test-train-split: 0.2
  batch size: 5
  t_in: 1
  t_out: 50
  step: 1

Opt:
  optimizer: 'adam'
  n_epochs: 500
  learning_rate: 0.005
  beta1: 0.9
  beta2: 0.9
  weight_decay: 1e-4
  scheduler: 'step'  # Or 'CosineAnnealingLR' OR 'ReduceLROnPlateau'
  scheduler_gamma: 0.5
  grad_clip: 2.0

Train: 
  loss: 'LP'
  rollout: True
  checkpoint:
    epochs: 50
  restart: False
  restart run name: 'dull-involute'

  
Simvue:
  mode: 'online'
  name: None # If None, config will be used but you can override it here
  folder: '/Neural_PDE/tests' 
