
seed: 907

Physics: 
  pde: 'Navier-Stokes'
  source: 'Spectral' 
  field: 'u, v, p'
  variables: 3
  Nx: 100
  Ny: 100
  Nt: 100
  dt: 0.01
  x_slice: 2
  y_slice: 2
  t_slice: 1
  physics normalisation: False

Model:
  arch: 'FNO'
  in_vars: 3
  out_vars: 3
  modes: 8
  width: 16
  n_layers: 6
  act: 'gelu'
  operator splitting: False

Data: 
  name: 'NS_Spectral_combined.npz'
  loc: '/home/ir-gopa2/rds/rds-ukaea-ap001/ir-gopa2/Code/Neural_PDE/Data'
  ntrain: 100
  test-train-split: 0.2
  batch size: 20
  t_in: 1
  t_out: 50
  step: 1
  normalisation: 'Min-Max'

Opt:
  optimizer: 'adam'
  epochs: 5
  learning rate: 0.005
  beta1: 0.9
  beta2: 0.9
  weight_decay: 1e-4
  scheduler: 'step'  
  scheduler step : 100
  scheduler gamma: 0.5
  grad_clip: 2.0

Train: 
  loss: 'LP'
  input_length: 1
  rollout_length: 30
  input_noise: 0.0
  odesolve: 
    source: 'torchdiffeq' #'torchdiffeq', 'custom'
    method: 'euler' # 'AR', 'euler', 'midpoint', rk4'
    adjoint: True #Only for torchdiffeq
  checkpoint:
    epochs: 100
  restart: False
  restart run name: '' #simvue run name 

Simvue:
  mode: 'online'
  name: None 
  folder: '/Neural_PDE/tests' 
